import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Container from './core/container';
import "./globals.css";
import TrackMap from './track-map';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Container>
         <TrackMap />
        </Container>
      </body>
    </html>
  );
}
